# Site settings
title: Zero2Flag
description: Ensinando conceitos de cybersecurity e hacking para pessoas que estão começando na área ou se interessam, por meio do jogo de Capture the Flag, um jeito divertido de aprender segurança na prática. 
cover: assets/images/background.jpeg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "/blog/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://zero2flag.github.io" # the base hostname & protocol for your site

pagination:

  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  per_page: 5

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
about: about
contact: contact


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate-v2


# Settings for rake task
safe: False
lsi: False
username: zero2flag #github username
repo: blog #github repository
branch: master #branch
relative_source: ../zero2flag/ #source directory
destination: ../zero2flag-pages/ #destination directory
production_url:  https://zero2flag.github.io/
source_url:  https://github.com/zero2flag/blog #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml